file_format: "1"
id: scatolotto
name: Scatolotto
type: shield
url: https://github.com/elvit/zmk-config-xiao_numpad
description: Bluetooth wireless numpad
requires:
  - pro_micro
features:
  - keys
  - encoder
outputs:
  - usb
  - ble
